//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaProductionEntities2 : DbContext
    {
        public MegaProductionEntities2()
            : base("name=MegaProductionEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DomaineMetier> DomaineMetiers { get; set; }
        public virtual DbSet<Metier> Metiers { get; set; }
        public virtual DbSet<OffreCasting> OffreCastings { get; set; }
        public virtual DbSet<PartenaireDiffusion> PartenaireDiffusions { get; set; }
        public virtual DbSet<TypeContrat> TypeContrats { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
