//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffreCasting
    {
        public long Identifiant { get; set; }
        public string Intitulé { get; set; }
        public string Reference { get; set; }
        public System.DateTime dateDebutPublication { get; set; }
        public System.DateTime dateDebutContrat { get; set; }
        public int dureeDiffusion { get; set; }
        public int nombreDePoste { get; set; }
        public string Localisation { get; set; }
        public string DescriptionPoste { get; set; }
        public string DescriptionProfilRecherche { get; set; }
        public Nullable<long> IdentifiantTypeContrat { get; set; }
        public Nullable<long> IdentifiantClient { get; set; }
        public Nullable<long> IdentifiantMetier { get; set; }
        public string Coordonne { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual TypeContrat TypeContrat { get; set; }
    }
}
